vim.loader.enable()
vim.g.mapleader = " "

require("plugins.gruvbox")
require("plugins.lualine")
require("plugins.plenary")
require("plugins.telescope")
require("plugins.dressing")
require("plugins.formatter")
require("plugins.nvim-lspconfig")
require("plugins.nvim-cmp")
require("plugins.mason")
require("plugins.mason-lspconfig")
require("plugins.mason-tool-installer")
require("plugins.luasnip")
require("plugins.friendly-snippets")
require("plugins.gitsigns")
require("plugins.trouble")
require("plugins.nvim-tree")
require("plugins.nvim-web-devicons")
require("plugins.fidget")
require("plugins.tree-sitter-manager")
require("plugins.nvim-ts-autotag")
require("plugins.nvim-treesitter-context")
require("plugins.nvim-autopairs")
require("plugins.vim-tmux-navigator")

require("core.options")
require("core.theme")
require("core.keymaps")
require("core.autocommands")
require("core.globals")
