return {
	"gisketch/triforce.nvim",
	dependencies = { "nvzone/volt" },
	opts = {
		levels = {
			{ level = 10, title = "Onbaşı" },
			{ level = 20, title = "Çavuş" },
			{ level = 30, title = "Uzman Onbaşı" },
			{ level = 40, title = "Uzman Çavuş" },
			{ level = 50, title = "Astsubay Astçavuş" },
			{ level = 60, title = "Astsubay Çavuş" },
			{ level = 70, title = "Astsubay Kıdemli Çavuş" },
			{ level = 80, title = "Astsubay Üstçavuş" },
			{ level = 90, title = "Astsubay Kıdemli Üstçavuş" },
			{ level = 100, title = "Astsubay Başçavuş" },
			{ level = 120, title = "Astsubay Kıdemli Başçavuş" },
			{ level = 150, title = "Asteğmen" },
			{ level = 180, title = "Teğmen" },
			{ level = 200, title = "Üsteğmen" },
			{ level = 250, title = "Yüzbaşı" },
			{ level = 300, title = "Binbaşı" },
			{ level = 350, title = "Yarbay" },
			{ level = 400, title = "Albay" },
			{ level = 450, title = "Tuğgeneral" },
			{ level = 500, title = "Tümgeneral" },
			{ level = 550, title = "Korgeneral" },
			{ level = 600, title = "Orgeneral" },
			{ level = 650, title = "Orgeneral" },
			{ level = 700, title = "Mareşal" },
		},
	},
}
