# Focus follows mouse
focus_follows_mouse yes
# Focus on alert
focus_on_window_activation focus

# Make the cursor move between focused containers
mouse_warping output

# Stop bluetooth
exec_always --no-startup-id /usr/bin/rfkill block bluetooth

# Start polkit agent
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 

# Colored window borders
default_border pixel 2
default_floating_border pixel 2
smart_borders on
