# Set shortname for gnome-schema
set $gnome-schema org.gnome.desktop.interface

# Set gruvbox colors
set $bg0 #282828
set $bg0_alpha #282828F2
set $bg2 #504945
set $red #CC241D
set $green #98971A
set $yellow #D79921
set $blue #458588
set $purple #B16286
set $aqua #689D68
set $orange #D65D0E
set $gray #A89984
set $white #FBF1C7
set $fg2 #DBC4A1

exec_always --no-startup-id gsettings set $gnome-schema gtk-theme 'gruvbox-dark-gtk'
exec_always --no-startup-id gsettings set $gnome-schema icon-theme 'gruvbox-dark-icons-gtk'
exec_always --no-startup-id gsettings set $gnome-schema cursor-theme 'Adwaita'
exec_always --no-startup-id gsettings set $gnome-schema font-name 'Noto Sans 11'
exec_always --no-startup-id gsettings set $gnome-schema monospace-font-name 'Noto Sans Mono 11'
exec_always --no-startup-id gsettings set $gnome-schema font-antialiasing 'rgba'
exec_always --no-startup-id gsettings set $gnome-schema font-hinting 'full'

# class                 border|backgr|text|indicator|child_border
client.focused          $blue $blue $bg0 $yellow $blue
client.focused_inactive $bg2 $bg0 $yellow $orange $bg2
client.unfocused        $bg2 $bg0 $yellow $orange $bg2
client.urgent           $red $red $white $red $red

font pango:Noto Sans Mono Bold 10

exec_always --no-startup-id /usr/bin/xsettingsd

exec_always --no-startup-id /usr/bin/feh --no-xinerama --bg-scale $HOME/pics/wall.jpg

 exec --no-startup-id picom

# add night light
